name: youtube
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Moved out of nested 'dev_dependencies' to fix redundancy

flutter:
  uses-material-design: true

  assets:
    - assets/virat.png
    - assets/kholi.jpg
    - assets/Virat4.jpg
